"""update employee detail

Revision ID: 510cd1da7f72
Revises: 364b2db73b87
Create Date: 2026-03-06 15:59:58.799714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510cd1da7f72'
down_revision = '364b2db73b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('division', sa.Enum('ys', 'yp', 'dev', name='division_name'), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_details')
    # ### end Alembic commands ###
