"""empty message

Revision ID: 81dc7b9217ee
Revises: a9a0200c52b1
Create Date: 2026-03-27 11:42:14.374451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81dc7b9217ee'
down_revision = 'a9a0200c52b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('medium_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('medium_url')
        batch_op.drop_column('original_url')

    # ### end Alembic commands ###
