"""update message

Revision ID: 89393af8bb46
Revises: 510cd1da7f72
Create Date: 2026-03-09 13:40:02.135724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89393af8bb46'
down_revision = '510cd1da7f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('/messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('number_phone', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('/messages')
    # ### end Alembic commands ###
