"""change column name

Revision ID: 91fbd08c7f52
Revises: cf69816b7458
Create Date: 2026-03-06 11:47:01.199000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91fbd08c7f52'
down_revision = 'cf69816b7458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=True))
        batch_op.drop_column('nama_lengkap')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_lengkap', mysql.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
