"""add phone column to users

Revision ID: c29d8d1b9736
Revises: 57c117dd0b0f
Create Date: 2026-03-05 14:10:12.462457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29d8d1b9736'
down_revision = '57c117dd0b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_phone', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['number_phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('number_phone')

    # ### end Alembic commands ###
