"""empty message

Revision ID: f9c99b116ff0
Revises: c9d78a31f49b
Create Date: 2026-03-13 15:24:01.539576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9c99b116ff0'
down_revision = 'c9d78a31f49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_images', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_images', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
